### ISSUE TITLE
Is this repo abandonned?

### ISSUE THREAD

**Issue by refactorized** [scijs/ndarray-ops#10]
It seems like there is little or no work coming in for this repo, yet I grabbed it along with several others mentioned here: http://scijs.net/packages/ as it seemed pretty essential to some of the experimental things I am doing with ndarray. 

I have been chasing my tail for a few hours trying to figure an out an odd bug that comes back to ndarray-ops::assign.  Now, I am wondering if it is worth the effort to try to correct the issue (PR), or if this particular repo is essentially abandoned in favor of just using cwise.

cwise on the other hand looks to have been updated 19 __minutes__ ago, at the time of following this issue, so that's great.

Either way thanks for the work so far.

**Comment by rreusser** [comment]
@refactorized Many of the ndarray modules are pretty stable, so although there's not active development going on, I wouldn't consider them abandoned. A number of the ndarray modules find their way into large projects ([e.g. plotly.js](https://github.com/plotly/plotly.js/blob/11bec79d010a44694bf70b357bd11e11ae874ccb/package-lock.json#L4552)) so that bug fixes are greatly appreciated and valued, though it can take a bit of effort to ensure that patch/minor/major semantic versioning is strictly adhered to. If PRs go unanswered, it may be the case that the authors/maintainers are distracted elsewhere, though—if I can frank—it's also very common that PRs have little explanation, failing tests, and inadequate justification for semvar-breaking changes.

If there's bug/fix to be reported, please do raise it! I don't have a lot of time to spend on things currently and I'm certainly guilty of having lost github notifications in the shuffle, but I'm glad to offer what assistance I can.

Also, you might be interested in [stdlib](https://github.com/stdlib-js/stdlib/). It has [an ndarray implementation](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray) with quite a bit of interesting functionality and environment support (js, native, wasm), though there's not yet a whole ecosystem of tools built on top of it.

**Comment by refactorized** [comment]
@rreusser Great to hear it, thanks for your reply.  Things do look stable and I have been enjoying a number of the ndarray libs this last week, so that's good news.  

I think I have found an actual bug, but on further inspection it seems to be with cwise.  ( for completeness the bug seems to be with traversal of a negatively stepped ndarray during assignment, I will try to put together a test case and submit it as an issue for that repo.

**Comment by refactorized** [comment]
Further news: I think that the issue was due to copying from an ndarray of one type to an ndarray of a different type, as I cannot reproduce in a test case now.  So that's more good news i guess.

**Comment by rreusser** [comment]
@refactorized That's great! I made this a long time ago to help provide some usage guidance. Let me know if you run into any issues! https://github.com/scijs/scijs-ndarray-for-matlab-users
